### ISSUE TITLE
rename master branch to mainline

### ISSUE THREAD

**Issue by Br3nda** [ODNZSL/nzsl-online#1038]
removing master/slave terminology from our tech

**Comment by Br3nda** [comment]
Same for other repos under ODNZSL

**Comment by eoinkelly** [comment]
Hearty :thumbsup:. Ackama is doing this across all our new projects - it seems like `main` is going to be the new default for Github and Gitlab (see https://gitlab.com/gitlab-org/gitlab/-/issues/221164) so we should probably use that here too.

**Comment by eoinkelly** [comment]
I'll hopefully have time to do it this weekend

**Comment by eoinkelly** [comment]
This has been completed for all ODNZSL repos. Please update your local remotes accordingly @Br3nda (and maybe @joshmcarthur )

**Comment by DSRU** [comment]
The README.txt under CONTRIBUTIONS still has a few references to 'Master'. Do those need to be updated accordingly?
