### ISSUE TITLE
investigate using gifv

### ISSUE THREAD

**Issue by Br3nda** [ODNZSL/nzsl-online#106]
videos in the dictionary do not have sound. It seems to me gifv is a perfect format for delivering silent videos. Given i'm happy to do the front end with in my 10% time, is the project happy to start using gifv?

**Comment by joshmcarthur** [comment]
Please correct me if I'm wrong, but I thought that gifv is just mp4 with a different extension? There are probably better video compression formats that can be used than mp4, however it does have the advantage of working everywhere - we'd need to also make sure that the Android and iOS applications could natively support gifv or any other format.

**Comment by Br3nda** [comment]
the api could serve up multiple formats --> and as the 3 clients (web,android,ios) start to support it, they'll switch over.

**Comment by Br3nda** [comment]
it is mp4 with a different extension -- but it causes browsers to treat it differently: they autoplay like an animated gif, and there's no sound.

**Comment by Br3nda** [comment]
Browsers are shifting to not allow autoplay -- so we may need to look at this issue seriously soon.

**Comment by Br3nda** [comment]
I had a chat with Dave, the maintainer of freelex about this. He's supportive of this. We can investigate this further and see how it will work.

**Comment by eoinkelly** [comment]
## Background on gifv

I did some research:

Details about `gifv` are bit hard to come by - https://blog.imgur.com//2014/10/09/introducing-gifv/ seems to be the introductory blog post but has very little detail. I was able to discover the following:

* a `.gifv` file is a plain-text HTML file - it is not a video file.
* When the `.gifv` HTML is rendered it mutates its DOM to create a `<video>` tag which contains `source` links to both an `mp4` version and a `webm` version
* gifv is solely an Imgur.com thing - there is no spec. Their intro blog post says:
    > Imgur plans to submit an accompanying specification to relevant standards organizations before the end of the year.

    but I have found no spec.
* `gifv` seems to be an attempt by Imgur to wrap mp4/webm in such a way that it behaves like a GIF when shared on social media platforms.
* The only way to create a gifv seems to be to upload a gif to Imgur at https://imgur.com/vidgif

**Comment by eoinkelly** [comment]
I think we'll be fine with autoplay for the near future at least because we don't have sound - see:

* Chrome https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
    > Muted autoplay is always allowed.
* Firefox https://support.mozilla.org/en-US/kb/block-autoplay
    > Firefox blocks all media with sound from playing automatically. 
* Edge https://www.pcworld.com/article/3292641/browsers/how-to-stop-autoplay-videos-in-microsoft-edge.html
    * It seems the user can choose whether they want autoplay or not

**Comment by Br3nda** [comment]
interesting! i understood it was just mp4. but i'm wrong

An animated gif might be a good idea, but perhaps it's not a good idea yet.

**Comment by Br3nda** [comment]
Let's close
