### ISSUE TITLE
Upgrade ruby version

### ISSUE THREAD

**Issue by Br3nda** [ODNZSL/nzsl-online#1252]
hey @G-Rath - any reason you've downgraded the ruby version back today?

**Comment by G-Rath** [comment]
@Br3nda see #1251 - deployments to staging were failing due to the ~`Gemfile.lock` not being updated~ heroku not running the app on Ruby 3:

```
-----> Installing dependencies using bundler 2.1.4
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Your Ruby version is 2.7.1, but your Gemfile specified 3.0.0
       Bundler Output: Your Ruby version is 2.7.1, but your Gemfile specified 3.0.0
 !
 !     Failed to install gems via Bundler.
 !     Detected a mismatch between your Ruby version installed and
 !     Ruby version specified in Gemfile or Gemfile.lock. You can
 !     correct this by running:
 !     
 !     $ bundle update --ruby
 !     $ git add Gemfile.lock
 !     $ git commit -m "update ruby version"
 !     
 !     If this does not solve the issue please see this documentation:
 !     
 !     https://devcenter.heroku.com/articles/ruby-versions#your-ruby-version-is-x-but-your-gemfile-specified-y
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by G-Rath** [comment]
I think it should be enough to update the ruby version in the `Gemfile.lock`, which is still set to v2:

https://github.com/ODNZSL/nzsl-online/blob/8e56e222464ad77874b9c5536875c4a9fd05aac8/Gemfile.lock#L449

**Comment by Br3nda** [comment]
there's a button to upgrade the stack -- I was just upgrading when I saw you rolled it back - Shall we proceed again to upgrade it?

**Comment by Br3nda** [comment]
missed a word. There's a button in heroku. We're on heroku-18, but need to upgrade to heroku-20 to get ruby 3

**Comment by G-Rath** [comment]
> We're on heroku-18, but need to upgrade to heroku-20 to get ruby 3

That's not the impression I get from their [documentation](https://devcenter.heroku.com/articles/heroku-18-stack#language-runtimes); my understanding is that it comes from what's returned [when you run `bundle platform --ruby`](https://devcenter.heroku.com/articles/ruby-versions#ruby-version-specifiers).

It's possible I'm wrong however, so keen to find out what the actual things you need to do are (I've always found the heroku docs on this stuff to be just vague enough to not give me total confidence 😅)

It's low priority for us right now as the app is sitting comfortably on the current Ruby version, but I've got no problem with you championing the upgrade if you'd like to take it on 🙂

We should update that value in the `Gemfile.lock` regardless however.
