### ISSUE TITLE
Migrate issue queue to open source project

### ISSUE THREAD

**Issue by Br3nda** [ODNZSL/nzsl-online#136]
Can we have the bugs/issue list in the public - thus inviting contributions to the open source project.

**Comment by Br3nda** [comment]
@danieljauch I spoke to @elspeth-rabid , who said this was being worked on. Is there any progress to report?

**Comment by DSRU** [comment]
Initial high priority issues have been transferred. I will continue to add stories from the backlog / icebox. Need to clarify interaction between Waffle board and GitHub issue list.

**Comment by Br3nda** [comment]
Awesome. Okay if I close this one for now?

**Comment by DSRU** [comment]
Let’s leave it open until next week as a reminder that I need to review the stories.
