### ISSUE TITLE
Staging Site search does not work

### ISSUE THREAD

**Issue by KatieWright26** [ODNZSL/nzsl-online#139]
We are currently unable to search after the merge of the rails update.

The main issue seems to be that the Google Analytics setup is out of date, as `_gaq` is now undefined (per console error message).

`_gaq` is defined in `admin.html.haml`, and the error is being generated from `search_analytics.js:44`.

Staging should not be deployed unless this recent commit is reverted.

**Comment by Br3nda** [comment]
@katiewright26 was this fixed when we reverted the rails 5 work?

**Comment by Br3nda** [comment]
@KatieWright26 can i close this?

**Comment by Br3nda** [comment]
Closing. Katie can you re-open if there's still an issue here.
