### ISSUE TITLE
NZSL- 20. Bug on live, staging and dev. An error occurs when clicking the video play/pause button. Displays an error in Safari

### ISSUE THREAD

**Issue by louise-r-blue** [ODNZSL/nzsl-online#378]
Clicking the pause/play button on Demonstration video on the https://nzsl-staging.herokuapp.com/alphabet/ causes an error. 
May be a Safari specific bug.
One screenshot shows the web inspector out-put.
The link wrapped around the video has a href of "alphabet-wide" when it should be "#alphabet-wide".
The link wrapped around the video has a href of "alphabet-over-shoulder" when it should be "#alphabet-over-shoulder".
![video_stop_pause-error_in_safari](https://user-images.githubusercontent.com/15900463/46320861-cf1e3180-c63c-11e8-904e-fd9ad9611407.png)
![safari_video-error](https://user-images.githubusercontent.com/15900463/46320914-0b519200-c63d-11e8-9010-3716b847ea15.png)

**Comment by elspeth-rabid** [comment]
@Br3nda hey! Sorry I saw your comment too late, I should have refreshed the page before merging!
This is still an issue but I can see if anyone can look at it right away...

**Comment by Br3nda** [comment]
i was being hopeful. I don't have access to safari, so i can't test this one.

**Comment by Br3nda** [comment]
note for testers, the production url is https://www.nzsl.nz/alphabet/

**Comment by kayakr** [comment]
I visited https://www.nzsl.nz/alphabet/ with Safari, but when I click on the video play icon I get the error reported above, e.g. browser goes to https://www.nzsl.nz/alphabet/alphabet-wide and returns 404. In Chrome, the video plays ok.

**Comment by Br3nda** [comment]
Thanks @kayakr. The fix will go live when #855 is merged
