### ISSUE TITLE
NZSL - 24 Differentiation between Maori and English glosses in mobile

### ISSUE THREAD

**Issue by louise-r-blue** [ODNZSL/nzsl-online#381]
On Desktop browsers there is differentiation between Māori and English glosses in that the Māori gloss text is italicised as in the screenshot below. The same behaviour is desired in mobile view.

![english_and _maori_glosses](https://user-images.githubusercontent.com/15900463/46327209-f2f16f80-c65c-11e8-8def-f79f04b5283e.png)

**Comment by DSRU** [comment]
Working on Android

**Comment by DSRU** [comment]
This issue probably relates to the mobile apps rather than the mobile view of the website.  Are we maintaining a separate issue list for nzsl-dictionary-android and nzsl-dictionary-ios?

**Comment by Br3nda** [comment]
Agreed. It's italicised correctly. Let's close this.

**Comment by DSRU** [comment]
Agreed.
