### ISSUE TITLE
NZSL - 23 CodeClimate cleanup

### ISSUE THREAD

**Issue by louise-r-blue** [ODNZSL/nzsl-online#384]
Ideally, this would sweep the entire application and clean up all issues that CodeClimate has been bringing up.

More immediately, the work done on NZSL‌-14 brought out a lot of issues that went unaddressed for the sake of the sprint.

- CSS class names need to be converted to BEM style: `block-name__element-name--modifier-name`

- Places where css properties are overridden should be better arranged to allow the cascade to create priority so that we don't need `!important`‌s

- CSS classes are added to elements so that rules can be applied to views without needing vague or conflict-prone CSS rules

**Comment by Br3nda** [comment]
Link to codeclimate issues: https://codeclimate.com/github/ODNZSL/nzsl-online

**Comment by eoinkelly** [comment]
I collected some stats

```
Total issues:   1647
Ruby issues:   14
JS issues:       109
SCSS issues: 1524
```

**Comment by eoinkelly** [comment]
Codeclimate issues update:

* Total issues: 512

made up of

* Ruby issues: 14
* JS issues: 109
* SCSS issues: 389

**Comment by eoinkelly** [comment]
Codeclimate has 146 issues total now https://codeclimate.com/github/ODNZSL/nzsl-online/issues

**Comment by Br3nda** [comment]
Nice work

**Comment by G-Rath** [comment]
We're no longer using CodeClimate for this project
