### ISSUE TITLE
Limiting of autocomplete search results not working

### ISSUE THREAD

**Issue by eoinkelly** [ODNZSL/nzsl-online#490]
From my testing it looks like the autocomplete search at `http://nzsl-assets.vuw.ac.nz/dnzsl/ncbin/public_search_lookup` ignores the `limit=10` param we send e.g. this is what I get when the search term is `hea`

```
Received 36 autocomplete suggestions (26 more than expected):
  ["heal", "head", "heat", "hear", "heavy", "heart", "health", "heater", "heaven", "header", "headway", "healthy", "heating", "hearing", "heading", "head for", "headache", "headline", "head lice", "heartburn", "heartbeat", "heartache", "headmaster", "heart rate", "headphones", "hearing aid", "heartbroken", "heart attack", "head teacher", "headquarters", "head spinning", "heavy drinker", "hearing school", "hearing impaired", "hearing aid battery", "hearing aid amplifier"]
```

This can be replicated by

```
$ curl  "http://nzsl-assets.vuw.ac.nz/dnzsl/ncbin/public_search_lookup?q=hea&limit=10"
heal
head
heat
hear
heavy
heart
health
heater
heaven
header
headway
healthy
heating
hearing
heading
head for
headache
headline
head lice
heartburn
heartbeat
heartache
headmaster
heart rate
headphones
hearing aid
heartbroken
heart attack
head teacher
headquarters
head spinning
heavy drinker
hearing school
hearing impaired
hearing aid battery
hearing aid amplifier
```

Are there any docs/code I can look at to see what the deal is there? Are we passing the limit param incorrectly? Does this endpoint actually support a limit?

This doesn't currently impact users of this app because we are trimming the results before sending them to the browser but it would be better to just ask for the correct number if possible.

**Comment by eoinkelly** [comment]
Update: We have been in touch with the maintainer of Freelex. They are fixing this issue and will let us know when it hits production.

**Comment by DSRU** [comment]
@eoinkelly on staging it does look like the autocomplete results are now limited to 10. Is it necessary to limit the results though? It is quite useful to show all possible results to encourage 'browsing' behaviour. If a limit is desirable, then could the top 10 autocomplete options be ordered in alphabetical order rather than by length?

**Comment by eoinkelly** [comment]
I don't have strong opinion about the limiting. I implemented the limiting in the controller because we were passing `limit=10` to Freelex so I assumed limiting to 10 was desired behaviour.

**Comment by Br3nda** [comment]
How about we set the limit to a much larger number?
IIRC we put it in config, so we can just change the ENV on heroku

**Comment by DSRU** [comment]
Was the limit put into place because the autocomplete was slowing down returning search results? If there are no efficiency gains then I'd suggest having a larger limit (or no limit).

**Comment by eoinkelly** [comment]
I think we probably still want a limit because 

The popup might obscure a lot of the page on small screens if there is no limit - I don't know if this is a think we should care about or not. The limit isn't in config but it is a fairly trivial code change. I'm happy to implement the change. @DSRU do you want to make a call on this?

**Comment by DSRU** [comment]
@eoinkelly it only obscures the page until 'search' is pressed. While using the search box, people don't need to see the content behind it. Are there any other reasons for imposing a limit?
If there are, then see my suggestion above: order the top 10 autocomplete options in alphabetical order rather than by word length.

**Comment by eoinkelly** [comment]
We still have this because we are waiting on a promised change to Freelex. Given the recent changes to autocomplete I'm not sure we care anymore. I would be happy to close this. What do you think @DSRU @Br3nda ?

**Comment by Br3nda** [comment]
I support closing this for now.

**Comment by DSRU** [comment]
Yes, let's close it for now.
