### ISSUE TITLE
point nzsl.nz at the website also

### ISSUE THREAD

**Issue by Br3nda** [ODNZSL/nzsl-online#494]
currently only www.nzsl.nz will reach the dictionary website

it would be nice to have https://nzsl.nz too.

**Comment by eoinkelly** [comment]
I agree. We would need to move the name servers from Iwantmyname - they don't support ALIAS records (https://help.iwantmyname.com/customer/portal/articles/1599947-do-you-support-alias-or-aname-dns-records- ) 😢 . I'm about to write up an issue suggesting we setup Cloudflare as a CDN - if we did that then Cloudflare would have the nameservers and we could make this change too.

**Comment by Br3nda** [comment]
They do support CNAME, which should be enough for now

**Comment by eoinkelly** [comment]
CNAME doesn't work for the root domain i.e. the domain without any subdomain prefix - there is some background in https://help.iwantmyname.com/customer/portal/articles/1599947-do-you-support-alias-or-aname-dns-records-

**Comment by DSRU** [comment]
http://nzsl.nz gets redirected to https://www.nzsl.nz at the moment, but https://nzsl.nz doesn't.

**Comment by eoinkelly** [comment]
This works now :tada:
