### ISSUE TITLE
Use Cloudflare as a CDN

### ISSUE THREAD

**Issue by eoinkelly** [ODNZSL/nzsl-online#495]
I think there would be a lot of benefit of using a CDN (Content Delivery Network) like Cloudflare for this site.  The benefits I see are

1. Cloudflare has edge locations much closer to NZ than the Heroku servers. Users of the site should notice a **significant** increase in page load speed.
1. Greatly reduced load on the rails app. Currently the rails app serves dynamic page content and all the static assets. A CDN would mean that most of the static asset traffic would not reach the rails servers. This would give us a lot more headroom for handling spikes in load.

Cloudflare has a **free plan** which I believe would be sufficient for this site so there would be no extra monthly hosting costs. I am happy to do the work of setting it up. Ackama has used Cloudflare a number of times in the past and have found it to be reliable and easy to configure.

I suggest the following steps

- [ ] Move the name-servers from IWantMyName to Cloudflare - the domain registration would stay with IWantMyName - (name-servers and domain registration are separate things). This also unblocks issue #494.
- [ ] Decide how long Cloudflare should cache assets for. 
- [ ] Configure the **staging** site to use Cloudflare and live with that for a while before we consider moving production - this will allow us to work out any issues which might crop up without impacting production.
- [ ] If we are happy with how the staging CDN performs then we configure production to use Cloudflare too.

**Comment by Br3nda** [comment]
I love this idea and it is worth testing

**Comment by eoinkelly** [comment]
As of this morning we are using Cloudflare as CDN - pages load quite a bit faster for me 👍 .
