### ISSUE TITLE
Make the numbers page a static page

### ISSUE THREAD

**Issue by eoinkelly** [ODNZSL/nzsl-online#576]
https://www.nzsl.nz/numbers currently pulls data from Freelex but the data never changes. @DSRU suggested we make this a static page and that seems sensible.

**Comment by DSRU** [comment]
I have put all the necessary drawings for this page on Google Drive: https://drive.google.com/drive/folders/1cndFT0rP37ODOyqiRIvi97wp2144EdqP?usp=sharing
