### ISSUE TITLE
Errors when fetching random signs, frequently happens during test runs.

### ISSUE THREAD

**Issue by Br3nda** [ODNZSL/nzsl-online#645]
Errors when fetching random signs, frequently happens during test runs.

```
  2) Sign .sign_of_the_day returns the same sign when called repeatedly
     Failure/Error:
       Rails.cache.fetch('sign-of-the-day', expires_in: 24.hours) do
         Rails.logger.debug('Fetching new random sign from Freelex')
         random
       end
     TypeError:
       can't dump MatchData
     # ./app/models/sign.rb:71:in `sign_of_the_day'
     # ./spec/models/sign_spec.rb:66:in `block (3 levels) in <top (required)>'
```

We should probably mock the test, so i doesn't hit freelex. 

But also would be nice to know what about the response is causing errors.

**Comment by eoinkelly** [comment]
I can't be certain but I suspect that the change to how Rails cache is setup I made in PR #732 may fix this.

**Comment by eoinkelly** [comment]
I'm pretty confident this won't happen anymore. We now JSON encode signs before putting them in the cache rather than relying on Ruby to `Marshal.dump` them.

**Comment by eoinkelly** [comment]
Going to close this because it hasn't happened in ages and I'm 99% sure I fixed it. We can re-open if it happens again
