### ISSUE TITLE
Store vocab sheet items inline in vocab_sheets table to stay within heroku DB plan row limits

### ISSUE THREAD

**Issue by eoinkelly** [ODNZSL/nzsl-online#698]
Currently `VocabSheet` has many `Item` and during busy times the number of items stored can take us up to and over the 10k DB rows limit on our Heroku DB plan. Using a different plan isn't within the budget in the medium term so we should change items to be stored inline (possibly as a jsonb) in the VocabSheet model.

**Comment by eoinkelly** [comment]
I can't remember exactly who proposed this initially (maybe @Br3nda or @elspeth-rabid ?) but it's a good workaround for budget constraints.

**Comment by eoinkelly** [comment]
I'm working on a PR for this btw, should be ready for review sometime this week.

**Comment by Br3nda** [comment]
Another approach could be adding a free tier no-sql database for storing these. Something like Cassandra or couchdb or elastic (or ... some disk backed memcache like thing).
