### ISSUE TITLE
Upgrade to Rails 6

### ISSUE THREAD

**Issue by eoinkelly** [ODNZSL/nzsl-online#748]
I have started a branch for this https://github.com/ODNZSL/nzsl-online/compare/ops/upgrade-rails-6?expand=1

This is currently blocked waiting on https://github.com/tsechingho/ckeditor-rails/pull/89 to land in the `ckeditor_rails` gem.

**Comment by Br3nda** [comment]
ckeditor has updated. Unblocked

**Comment by eoinkelly** [comment]
See PR #1005
